// ITEMS
export const PRODUCT_TO_ITEM =  "PRODUCT_TO_ITEM"
export const ITEM_ADD_QUANTITY = "ITEM_ADD_QUANTITY"
export const ITEM_CHANGE_QUANTITY = "ITEM_CHANGE_QUANTITY"
export const ADD_ITEM = "ADD_ITEM"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const CHANGE_ITEM = "CHANGE_ITEM"
export const CHANGE_CURRENT_ITEM = "CHANGE_CURRENT_ITEM"

export const API = "API"
export const API_START = "API_START"
export const API_END = "API_END"
export const ACCESS_DENIED = "ACCESS_DENIED"
export const API_ERROR  = "API_ERROR"

export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const SET_PRODUCTS = "SET_PRODUCTS"
export const FETCH_PRODUCT = "FETCH_PRODUCT"

export const GENERATE_CODE = "GENERATE_CODE"
export const UPDATE_CODE = "UPDATE_CODE"
export const FETCH_EXAMPLE = "FETCH_EXAMPLE"
// export const SET_CODE = "SET_CODE"
export const MODIFY_CODE = "MODIFY_CODE"

export const COMPILE_GOCODE = "COMPILE_GOCODE"
export const EVALUATED_CODE = "EVALUATED_CODE"
export const COMPILE_FAILED = "COMPILE_FAILED"
export const EVALUATED_CODE_ERRORS = "EVALUATED_CODE_ERRORS"
export const VET_GOCODE = "VET_GOCODE"

export const ADD_PRODUCT_TO_CODE = "ADD_PRODUCT_TO_CODE"
export const ADD_ITEM_TO_CODE = "ADD_ITEM_TO_CODE"
export const SPLIT_CODE_WIDTH = "SPLIT_CODE_WIDTH"

// Effects
export const EFFECT_NEED_COMPILE = "EFFECT_NEED_COMPILE"
export const APPLY_EFFECT = "APPLY_EFFECT"
export const RESET_EFFECT = "RESET_EFFECT"
export const APPLY_CURRENT_EFFECTS = "APPLY_CURRENT_EFFECTS"